package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/asn1"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"math/big"
	"net/http"
	"sort"
	"strings"

	"github.com/edgelesssys/ego/enclave"
)

// Global signing key for this enclave instance (Ephemeral, generated on startup)
var privateKey *ecdsa.PrivateKey
var publicKey []byte

// Global encryption key for this enclave instance (Ephemeral, RSA-2048)
var decryptionKey *rsa.PrivateKey

func init() {
	var err error
	// Generate an ephemeral P-256 key pair for this enclave session
	privateKey, err = ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		log.Fatalf("Failed to generate enclave signing key: %v", err)
	}
	// Marshal public key to bytes (uncompressed)
	publicKey = elliptic.Marshal(privateKey.Curve, privateKey.PublicKey.X, privateKey.PublicKey.Y)

	// Generate ephemeral RSA key for encryption (frontend will encrypt clicks with this)
	decryptionKey, err = rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		log.Fatalf("Failed to generate enclave encryption key: %v", err)
	}
}

// Click represents a player's action with a timestamp.
type Click struct {
	Ciphertext   string `json:"ciphertext"`   // Hex encoded encrypted JSON {"playerAddress": "..."}
	ReactionTime int64  `json:"reactionTime"` // Nanoseconds (recorded by backend upon receipt)
}

// GameResultRequest is the payload sent by the main backend.
type GameResultRequest struct {
	GameID           string   `json:"gameId"`
	DepositedPlayers []string `json:"depositedPlayers"`
	Clicks           []Click  `json:"clicks"`
	MinPlayers       int      `json:"minPlayers"`
}

// GameResultResponse is the signed result returned by the enclave.
type GameResultResponse struct {
	Winners         []string         `json:"winners"`
	Loser           string           `json:"loser"`
	DecryptedClicks map[string]int64 `json:"decryptedClicks"` // NEW: Map address to reaction time
	Signature       string           `json:"signature"`       // Hex encoded signature of the result
	PublicKey       string           `json:"publicKey"`       // Hex encoded public key (for verification)
	EncryptionKey   string           `json:"encryptionKey"`   // PEM encoded RSA public key
	Error           string           `json:"error,omitempty"`
}

func main() {
	// EGo can terminate TLS inside the enclave, ensuring the request reaches the secure environment directly.
	// We use Attested TLS to allow the client to verify the enclave's identity and integrity.
	http.HandleFunc("/api/result", handleDetermineResult)
	http.HandleFunc("/api/attestation", handleAttestation)

	port := "8081"
	fmt.Printf("Enclave Service listening on port %s (HTTP)...\n", port)

	// TLS is disabled for internal Docker communication.
	// Attestation verification should be done by checking the report payload from /api/attestation.

	server := &http.Server{
		Addr: ":" + port,
	}

	log.Fatal(server.ListenAndServe())
}

func handleAttestation(w http.ResponseWriter, r *http.Request) {
	// Get nonce from query parameter to prevent replay attacks
	nonce := r.URL.Query().Get("nonce")

	// Bind the ephemeral Signing Key AND Encryption Key AND the client's Nonce to the report.
	// ReportData = SHA256(SigningPubKey || EncryptionPubKey || Nonce)
	// This proves that the report was generated by an enclave holding the private key corresponding to this public key.
	hasher := sha256.New()
	hasher.Write(publicKey)
	hasher.Write(x509.MarshalPKCS1PublicKey(&decryptionKey.PublicKey)) // Bind encryption key too
	if nonce != "" {
		hasher.Write([]byte(nonce))
	}
	// SGX ReportData is 64 bytes. SHA256 is 32 bytes, so it fits easily.
	reportData := make([]byte, 64)
	copy(reportData, hasher.Sum(nil))

	// Generate a remote report to prove this code is running in SGX.
	// You can include a nonce or public key in the report data to bind it to a specific session/key.
	report, err := enclave.GetRemoteReport(reportData)
	if err != nil {
		http.Error(w, fmt.Sprintf("Failed to get attestation report: %v", err), http.StatusInternalServerError)
		return
	}

	// Export RSA public key as PEM string for easy use in frontend
	// Use PKIX (SPKI) for better compatibility with Web Crypto API
	rsaPubBytes, err := x509.MarshalPKIXPublicKey(&decryptionKey.PublicKey)
	if err != nil {
		http.Error(w, "Failed to marshal encryption key", http.StatusInternalServerError)
		return
	}
	rsaPubHex := hex.EncodeToString(rsaPubBytes)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"report":        fmt.Sprintf("%x", report),
		"publicKey":     hex.EncodeToString(publicKey), // Signing key
		"encryptionKey": rsaPubHex,                     // Encryption key (RSA)
	})
}

func handleDetermineResult(w http.ResponseWriter, r *http.Request) {
	var req GameResultRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		log.Printf("handleDetermineResult: Error decoding request body: %v", err)
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	winners, loser, decryptedClicks, err := determineWinnersAndLoser(req)
	if err != nil {
		json.NewEncoder(w).Encode(GameResultResponse{Error: err.Error()})
		return
	}

	// Sign the result to ensure authenticity
	// Data to sign: Loser + Winners (joined)
	// In a real app, you'd sign a canonical JSON or hash of the full struct.
	dataToSign := []byte(loser + strings.Join(winners, ""))
	hash := sha256.Sum256(dataToSign)
	rSig, sSig, err := ecdsa.Sign(rand.Reader, privateKey, hash[:])
	signature := ""
	if err == nil {
		sigBytes, _ := asn1.Marshal(struct{ R, S *big.Int }{rSig, sSig})
		signature = hex.EncodeToString(sigBytes)
	}

	// Export RSA public key
	rsaPubBytes, _ := x509.MarshalPKIXPublicKey(&decryptionKey.PublicKey)

	resp := GameResultResponse{
		Winners:         winners,
		Loser:           loser,
		DecryptedClicks: decryptedClicks,
		Signature:       signature,
		PublicKey:       hex.EncodeToString(publicKey),
		EncryptionKey:   hex.EncodeToString(rsaPubBytes),
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

// determineWinnersAndLoser contains the core logic moved from the main backend.
func determineWinnersAndLoser(req GameResultRequest) ([]string, string, map[string]int64, error) {
	log.Printf("determineWinnersAndLoser: Processing game %s. Clicks: %d, Deposited: %d", req.GameID, len(req.Clicks), len(req.DepositedPlayers))

	if len(req.DepositedPlayers) < req.MinPlayers {
		return nil, "", nil, fmt.Errorf("not enough deposited players (%d/%d)", len(req.DepositedPlayers), req.MinPlayers)
	}

	// Decrypt clicks and map them
	clickedMap := make(map[string]bool)
	decryptedClicks := make(map[string]int64)
	validClicks := []Click{} // Store decrypted clicks for sorting

	for i, c := range req.Clicks {
		// Decode hex ciphertext
		ciphertext, err := hex.DecodeString(c.Ciphertext)
		if err != nil {
			log.Printf("determineWinnersAndLoser: Click %d hex decode failed: %v", i, err)
			continue // Skip invalid hex
		}

		// Decrypt using RSA-OAEP
		plaintext, err := rsa.DecryptOAEP(sha256.New(), rand.Reader, decryptionKey, ciphertext, nil)
		if err != nil {
			log.Printf("determineWinnersAndLoser: Click %d decryption failed: %v. Data len: %d", i, err, len(ciphertext))
			continue // Skip invalid decryption (wrong key or corrupted)
		}

		// Parse JSON: {"playerAddress": "0x..."}
		var payload struct {
			PlayerAddress string `json:"playerAddress"`
		}
		if err := json.Unmarshal(plaintext, &payload); err != nil {
			log.Printf("determineWinnersAndLoser: Click %d JSON error: %v. Raw: %s", i, err, string(plaintext))
		} else if payload.PlayerAddress == "" {
			log.Printf("determineWinnersAndLoser: Click %d has empty address", i)
		} else {
			addrLower := strings.ToLower(payload.PlayerAddress)
			log.Printf("determineWinnersAndLoser: Click %d success for: %s", i, addrLower)
			clickedMap[addrLower] = true
			decryptedClicks[addrLower] = c.ReactionTime
			// Store valid click with original timestamp for sorting
			// We reuse the Click struct but conceptually we are storing the decrypted address now
			// Note: We can't modify c.Ciphertext to be address, so we create a new list or map.
			// Let's just use a map for "who clicked" and a slice for "order".
			// Actually, we need to sort by ReactionTime.
			// Let's create a temporary struct for sorting.
			validClicks = append(validClicks, Click{Ciphertext: addrLower, ReactionTime: c.ReactionTime}) // Hack: storing addr in Ciphertext field for internal sorting
		}
	}

	// Identify who did NOT click
	depositedButNotClicked := []string{}
	for _, addr := range req.DepositedPlayers {
		lowerAddr := strings.ToLower(addr)
		if !clickedMap[lowerAddr] {
			depositedButNotClicked = append(depositedButNotClicked, lowerAddr)
		}
	}
	log.Printf("determineWinnersAndLoser: Players considered non-clickers: %v", depositedButNotClicked)

	var loser string

	// Logic to determine loser
	if len(depositedButNotClicked) > 0 {
		// If some people didn't click, one of them loses.
		// We use crypto/rand inside the enclave for secure randomness.
		maxIndex := big.NewInt(int64(len(depositedButNotClicked)))
		nBig, err := rand.Int(rand.Reader, maxIndex)
		if err != nil {
			// Fallback (should be extremely rare)
			loser = depositedButNotClicked[0]
		} else {
			loser = depositedButNotClicked[nBig.Int64()]
		}
	} else {
		// Everyone clicked. The LAST person to click loses.
		// Sort clicks by reaction time (descending) to find the slowest.
		// Note: We trust the timestamps provided by the backend, but the sorting logic is guaranteed here.
		// Ideally, the enclave would measure time, but that requires moving the WebSocket connection here.
		sort.Slice(validClicks, func(i, j int) bool {
			return validClicks[i].ReactionTime > validClicks[j].ReactionTime
		})

		// The first element is now the one with the largest (slowest) reaction time
		// But we must ensure the clicker is actually a deposited player
		for _, click := range validClicks {
			clickerAddr := click.Ciphertext // We stored address here above
			isDeposited := false
			for _, dp := range req.DepositedPlayers {
				if strings.ToLower(dp) == clickerAddr {
					isDeposited = true
					break
				}
			}
			if isDeposited {
				loser = clickerAddr
				break
			}
		}
	}

	if loser == "" {
		return nil, "", nil, fmt.Errorf("could not determine loser")
	}

	// Determine winners (everyone else)
	winners := []string{}
	for _, addr := range req.DepositedPlayers {
		lowerAddr := strings.ToLower(addr)
		if lowerAddr != loser {
			winners = append(winners, lowerAddr)
		}
	}
	sort.Strings(winners) // Deterministic order

	return winners, loser, decryptedClicks, nil
}
